version: '3.7'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/shared
    working_dir: /shared/blog
    ports:
      - '8080:8080'
    command:
      yarn serve
  api:
    build: api
    volumes:
      - ./:/shared
    working_dir: /shared/api
    ports:
      - '5000:5000'
    command:
      python app.py